# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python\y-str\Y-str\mainframe.ui'
#
# Created: Wed Aug 29 16:46:41 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(922, 768)
        MainWindow.setMinimumSize(QtCore.QSize(922, 768))
        MainWindow.setMaximumSize(QtCore.QSize(922, 768))
        MainWindow.setAnimated(True)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 901, 191))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.checkBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_5 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_5.setGeometry(QtCore.QRect(370, 20, 71, 16))
        self.checkBox_5.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.checkBox_7 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_7.setGeometry(QtCore.QRect(550, 20, 71, 16))
        self.checkBox_7.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.checkBox_12 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_12.setGeometry(QtCore.QRect(100, 70, 71, 16))
        self.checkBox_12.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.checkBox_16 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_16.setGeometry(QtCore.QRect(460, 70, 71, 16))
        self.checkBox_16.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_16.setObjectName(_fromUtf8("checkBox_16"))
        self.checkBox_10 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_10.setGeometry(QtCore.QRect(820, 20, 71, 16))
        self.checkBox_10.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.checkBox_18 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_18.setGeometry(QtCore.QRect(640, 70, 71, 16))
        self.checkBox_18.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.checkBox_11 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_11.setGeometry(QtCore.QRect(10, 70, 71, 16))
        self.checkBox_11.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.checkBox_8 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_8.setGeometry(QtCore.QRect(640, 20, 71, 16))
        self.checkBox_8.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.checkBox_9 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_9.setGeometry(QtCore.QRect(730, 20, 71, 16))
        self.checkBox_9.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.checkBox_19 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_19.setGeometry(QtCore.QRect(730, 70, 71, 16))
        self.checkBox_19.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_19.setObjectName(_fromUtf8("checkBox_19"))
        self.checkBox_13 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_13.setGeometry(QtCore.QRect(190, 70, 71, 16))
        self.checkBox_13.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.checkBox_14 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_14.setGeometry(QtCore.QRect(280, 70, 71, 16))
        self.checkBox_14.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.checkBox_17 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_17.setGeometry(QtCore.QRect(550, 70, 71, 16))
        self.checkBox_17.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_17.setObjectName(_fromUtf8("checkBox_17"))
        self.checkBox_4 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_4.setGeometry(QtCore.QRect(280, 20, 71, 16))
        self.checkBox_4.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.checkBox_6 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_6.setGeometry(QtCore.QRect(460, 20, 71, 16))
        self.checkBox_6.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(100, 20, 81, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_15 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_15.setGeometry(QtCore.QRect(370, 70, 71, 16))
        self.checkBox_15.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_15.setObjectName(_fromUtf8("checkBox_15"))
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(190, 20, 71, 16))
        self.checkBox_3.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_20 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_20.setGeometry(QtCore.QRect(820, 70, 71, 16))
        self.checkBox_20.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.checkBox_21 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_21.setGeometry(QtCore.QRect(10, 120, 71, 16))
        self.checkBox_21.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.checkBox_22 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_22.setGeometry(QtCore.QRect(100, 120, 71, 16))
        self.checkBox_22.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_22.setObjectName(_fromUtf8("checkBox_22"))
        self.checkBox_23 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_23.setGeometry(QtCore.QRect(190, 120, 71, 16))
        self.checkBox_23.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_23.setObjectName(_fromUtf8("checkBox_23"))
        self.checkBox_24 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_24.setGeometry(QtCore.QRect(280, 120, 71, 16))
        self.checkBox_24.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_24.setObjectName(_fromUtf8("checkBox_24"))
        self.checkBox_25 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_25.setGeometry(QtCore.QRect(370, 120, 71, 16))
        self.checkBox_25.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_25.setObjectName(_fromUtf8("checkBox_25"))
        self.checkBox_26 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_26.setGeometry(QtCore.QRect(460, 120, 71, 16))
        self.checkBox_26.setMaximumSize(QtCore.QSize(71, 16777215))
        self.checkBox_26.setObjectName(_fromUtf8("checkBox_26"))
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(820, 150, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.spinBox = QtGui.QSpinBox(self.groupBox)
        self.spinBox.setEnabled(False)
        self.spinBox.setGeometry(QtCore.QRect(10, 40, 42, 22))
        self.spinBox.setProperty("value", 10)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.spinBox_2 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_2.setEnabled(False)
        self.spinBox_2.setGeometry(QtCore.QRect(100, 40, 42, 22))
        self.spinBox_2.setProperty("value", 10)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.spinBox_3 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_3.setEnabled(False)
        self.spinBox_3.setGeometry(QtCore.QRect(190, 40, 42, 22))
        self.spinBox_3.setProperty("value", 10)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.spinBox_4 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_4.setEnabled(False)
        self.spinBox_4.setGeometry(QtCore.QRect(370, 40, 42, 22))
        self.spinBox_4.setProperty("value", 10)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.spinBox_5 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_5.setEnabled(False)
        self.spinBox_5.setGeometry(QtCore.QRect(280, 40, 42, 22))
        self.spinBox_5.setProperty("value", 10)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.spinBox_6 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_6.setEnabled(False)
        self.spinBox_6.setGeometry(QtCore.QRect(460, 40, 42, 22))
        self.spinBox_6.setProperty("value", 10)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.spinBox_7 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_7.setEnabled(False)
        self.spinBox_7.setGeometry(QtCore.QRect(550, 40, 42, 22))
        self.spinBox_7.setProperty("value", 10)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.spinBox_8 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_8.setEnabled(False)
        self.spinBox_8.setGeometry(QtCore.QRect(640, 40, 42, 22))
        self.spinBox_8.setProperty("value", 10)
        self.spinBox_8.setObjectName(_fromUtf8("spinBox_8"))
        self.spinBox_9 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_9.setEnabled(False)
        self.spinBox_9.setGeometry(QtCore.QRect(730, 40, 42, 22))
        self.spinBox_9.setProperty("value", 10)
        self.spinBox_9.setObjectName(_fromUtf8("spinBox_9"))
        self.spinBox_10 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_10.setEnabled(False)
        self.spinBox_10.setGeometry(QtCore.QRect(820, 40, 42, 22))
        self.spinBox_10.setProperty("value", 10)
        self.spinBox_10.setObjectName(_fromUtf8("spinBox_10"))
        self.spinBox_11 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_11.setEnabled(False)
        self.spinBox_11.setGeometry(QtCore.QRect(820, 90, 42, 22))
        self.spinBox_11.setProperty("value", 10)
        self.spinBox_11.setObjectName(_fromUtf8("spinBox_11"))
        self.spinBox_12 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_12.setEnabled(False)
        self.spinBox_12.setGeometry(QtCore.QRect(280, 90, 42, 22))
        self.spinBox_12.setProperty("value", 10)
        self.spinBox_12.setObjectName(_fromUtf8("spinBox_12"))
        self.spinBox_13 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_13.setEnabled(False)
        self.spinBox_13.setGeometry(QtCore.QRect(730, 90, 42, 22))
        self.spinBox_13.setProperty("value", 10)
        self.spinBox_13.setObjectName(_fromUtf8("spinBox_13"))
        self.spinBox_14 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_14.setEnabled(False)
        self.spinBox_14.setGeometry(QtCore.QRect(550, 90, 42, 22))
        self.spinBox_14.setProperty("value", 10)
        self.spinBox_14.setObjectName(_fromUtf8("spinBox_14"))
        self.spinBox_15 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_15.setEnabled(False)
        self.spinBox_15.setGeometry(QtCore.QRect(100, 90, 42, 22))
        self.spinBox_15.setProperty("value", 10)
        self.spinBox_15.setObjectName(_fromUtf8("spinBox_15"))
        self.spinBox_16 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_16.setEnabled(False)
        self.spinBox_16.setGeometry(QtCore.QRect(370, 90, 42, 22))
        self.spinBox_16.setProperty("value", 10)
        self.spinBox_16.setObjectName(_fromUtf8("spinBox_16"))
        self.spinBox_17 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_17.setEnabled(False)
        self.spinBox_17.setGeometry(QtCore.QRect(640, 90, 42, 22))
        self.spinBox_17.setProperty("value", 10)
        self.spinBox_17.setObjectName(_fromUtf8("spinBox_17"))
        self.spinBox_18 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_18.setEnabled(False)
        self.spinBox_18.setGeometry(QtCore.QRect(460, 90, 42, 22))
        self.spinBox_18.setProperty("value", 10)
        self.spinBox_18.setObjectName(_fromUtf8("spinBox_18"))
        self.spinBox_19 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_19.setEnabled(False)
        self.spinBox_19.setGeometry(QtCore.QRect(10, 90, 42, 22))
        self.spinBox_19.setProperty("value", 10)
        self.spinBox_19.setObjectName(_fromUtf8("spinBox_19"))
        self.spinBox_20 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_20.setEnabled(False)
        self.spinBox_20.setGeometry(QtCore.QRect(190, 90, 42, 22))
        self.spinBox_20.setProperty("value", 10)
        self.spinBox_20.setObjectName(_fromUtf8("spinBox_20"))
        self.spinBox_21 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_21.setEnabled(False)
        self.spinBox_21.setGeometry(QtCore.QRect(460, 140, 42, 22))
        self.spinBox_21.setProperty("value", 10)
        self.spinBox_21.setObjectName(_fromUtf8("spinBox_21"))
        self.spinBox_22 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_22.setEnabled(False)
        self.spinBox_22.setGeometry(QtCore.QRect(100, 140, 42, 22))
        self.spinBox_22.setProperty("value", 10)
        self.spinBox_22.setObjectName(_fromUtf8("spinBox_22"))
        self.spinBox_23 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_23.setEnabled(False)
        self.spinBox_23.setGeometry(QtCore.QRect(10, 140, 42, 22))
        self.spinBox_23.setProperty("value", 10)
        self.spinBox_23.setObjectName(_fromUtf8("spinBox_23"))
        self.spinBox_24 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_24.setEnabled(False)
        self.spinBox_24.setGeometry(QtCore.QRect(370, 140, 42, 22))
        self.spinBox_24.setProperty("value", 10)
        self.spinBox_24.setObjectName(_fromUtf8("spinBox_24"))
        self.spinBox_25 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_25.setEnabled(False)
        self.spinBox_25.setGeometry(QtCore.QRect(280, 140, 42, 22))
        self.spinBox_25.setProperty("value", 10)
        self.spinBox_25.setObjectName(_fromUtf8("spinBox_25"))
        self.spinBox_26 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_26.setEnabled(False)
        self.spinBox_26.setGeometry(QtCore.QRect(190, 140, 42, 22))
        self.spinBox_26.setProperty("value", 10)
        self.spinBox_26.setObjectName(_fromUtf8("spinBox_26"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QtCore.QRect(720, 150, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.tableWidget = QtGui.QTableWidget(self.centralWidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 200, 901, 541))
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox.setEnabled)
        QtCore.QObject.connect(self.checkBox_2, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_2.setEnabled)
        QtCore.QObject.connect(self.checkBox_3, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_3.setEnabled)
        QtCore.QObject.connect(self.checkBox_4, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_5.setEnabled)
        QtCore.QObject.connect(self.checkBox_5, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_4.setEnabled)
        QtCore.QObject.connect(self.checkBox_6, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_6.setEnabled)
        QtCore.QObject.connect(self.checkBox_7, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_7.setEnabled)
        QtCore.QObject.connect(self.checkBox_8, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_8.setEnabled)
        QtCore.QObject.connect(self.checkBox_9, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_9.setEnabled)
        QtCore.QObject.connect(self.checkBox_10, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_10.setEnabled)
        QtCore.QObject.connect(self.checkBox_11, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_19.setEnabled)
        QtCore.QObject.connect(self.checkBox_12, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_15.setEnabled)
        QtCore.QObject.connect(self.checkBox_13, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_20.setEnabled)
        QtCore.QObject.connect(self.checkBox_14, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_12.setEnabled)
        QtCore.QObject.connect(self.checkBox_15, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_16.setEnabled)
        QtCore.QObject.connect(self.checkBox_16, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_18.setEnabled)
        QtCore.QObject.connect(self.checkBox_17, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_14.setEnabled)
        QtCore.QObject.connect(self.checkBox_18, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_17.setEnabled)
        QtCore.QObject.connect(self.checkBox_19, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_13.setEnabled)
        QtCore.QObject.connect(self.checkBox_20, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_11.setEnabled)
        QtCore.QObject.connect(self.checkBox_21, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_23.setEnabled)
        QtCore.QObject.connect(self.checkBox_22, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_22.setEnabled)
        QtCore.QObject.connect(self.checkBox_23, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_26.setEnabled)
        QtCore.QObject.connect(self.checkBox_24, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_25.setEnabled)
        QtCore.QObject.connect(self.checkBox_26, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_21.setEnabled)
        QtCore.QObject.connect(self.checkBox_25, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spinBox_24.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.checkBox, self.spinBox)
        MainWindow.setTabOrder(self.spinBox, self.checkBox_2)
        MainWindow.setTabOrder(self.checkBox_2, self.spinBox_2)
        MainWindow.setTabOrder(self.spinBox_2, self.checkBox_3)
        MainWindow.setTabOrder(self.checkBox_3, self.spinBox_3)
        MainWindow.setTabOrder(self.spinBox_3, self.checkBox_4)
        MainWindow.setTabOrder(self.checkBox_4, self.spinBox_5)
        MainWindow.setTabOrder(self.spinBox_5, self.checkBox_5)
        MainWindow.setTabOrder(self.checkBox_5, self.spinBox_4)
        MainWindow.setTabOrder(self.spinBox_4, self.checkBox_6)
        MainWindow.setTabOrder(self.checkBox_6, self.spinBox_6)
        MainWindow.setTabOrder(self.spinBox_6, self.checkBox_7)
        MainWindow.setTabOrder(self.checkBox_7, self.spinBox_7)
        MainWindow.setTabOrder(self.spinBox_7, self.checkBox_8)
        MainWindow.setTabOrder(self.checkBox_8, self.spinBox_8)
        MainWindow.setTabOrder(self.spinBox_8, self.checkBox_9)
        MainWindow.setTabOrder(self.checkBox_9, self.spinBox_9)
        MainWindow.setTabOrder(self.spinBox_9, self.checkBox_10)
        MainWindow.setTabOrder(self.checkBox_10, self.spinBox_10)
        MainWindow.setTabOrder(self.spinBox_10, self.checkBox_11)
        MainWindow.setTabOrder(self.checkBox_11, self.spinBox_19)
        MainWindow.setTabOrder(self.spinBox_19, self.checkBox_12)
        MainWindow.setTabOrder(self.checkBox_12, self.spinBox_15)
        MainWindow.setTabOrder(self.spinBox_15, self.checkBox_13)
        MainWindow.setTabOrder(self.checkBox_13, self.spinBox_20)
        MainWindow.setTabOrder(self.spinBox_20, self.checkBox_14)
        MainWindow.setTabOrder(self.checkBox_14, self.spinBox_12)
        MainWindow.setTabOrder(self.spinBox_12, self.checkBox_15)
        MainWindow.setTabOrder(self.checkBox_15, self.spinBox_16)
        MainWindow.setTabOrder(self.spinBox_16, self.checkBox_16)
        MainWindow.setTabOrder(self.checkBox_16, self.spinBox_18)
        MainWindow.setTabOrder(self.spinBox_18, self.checkBox_17)
        MainWindow.setTabOrder(self.checkBox_17, self.spinBox_14)
        MainWindow.setTabOrder(self.spinBox_14, self.checkBox_18)
        MainWindow.setTabOrder(self.checkBox_18, self.spinBox_17)
        MainWindow.setTabOrder(self.spinBox_17, self.checkBox_19)
        MainWindow.setTabOrder(self.checkBox_19, self.spinBox_13)
        MainWindow.setTabOrder(self.spinBox_13, self.checkBox_20)
        MainWindow.setTabOrder(self.checkBox_20, self.spinBox_11)
        MainWindow.setTabOrder(self.spinBox_11, self.checkBox_21)
        MainWindow.setTabOrder(self.checkBox_21, self.spinBox_23)
        MainWindow.setTabOrder(self.spinBox_23, self.checkBox_22)
        MainWindow.setTabOrder(self.checkBox_22, self.spinBox_22)
        MainWindow.setTabOrder(self.spinBox_22, self.checkBox_23)
        MainWindow.setTabOrder(self.checkBox_23, self.spinBox_26)
        MainWindow.setTabOrder(self.spinBox_26, self.checkBox_24)
        MainWindow.setTabOrder(self.checkBox_24, self.spinBox_25)
        MainWindow.setTabOrder(self.spinBox_25, self.checkBox_25)
        MainWindow.setTabOrder(self.checkBox_25, self.spinBox_24)
        MainWindow.setTabOrder(self.spinBox_24, self.checkBox_26)
        MainWindow.setTabOrder(self.checkBox_26, self.spinBox_21)
        MainWindow.setTabOrder(self.spinBox_21, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.tableWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Y-str matching", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "DYS388", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("MainWindow", "DYS390", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setText(QtGui.QApplication.translate("MainWindow", "DYS392", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_12.setText(QtGui.QApplication.translate("MainWindow", "DYS435", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_16.setText(QtGui.QApplication.translate("MainWindow", "DYS439", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_10.setText(QtGui.QApplication.translate("MainWindow", "DYS426", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_18.setText(QtGui.QApplication.translate("MainWindow", "DYS385b", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_11.setText(QtGui.QApplication.translate("MainWindow", "DYS434", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_8.setText(QtGui.QApplication.translate("MainWindow", "DYS393", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_9.setText(QtGui.QApplication.translate("MainWindow", "DYS425", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_19.setText(QtGui.QApplication.translate("MainWindow", "DYSA7.2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_13.setText(QtGui.QApplication.translate("MainWindow", "DYS436", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_14.setText(QtGui.QApplication.translate("MainWindow", "DYS437", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_17.setText(QtGui.QApplication.translate("MainWindow", "DYS385a", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("MainWindow", "DYS389II", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("MainWindow", "DYS391", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("MainWindow", "DYS 19/394", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_15.setText(QtGui.QApplication.translate("MainWindow", "DYS438", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("MainWindow", "DYS389I", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_20.setText(QtGui.QApplication.translate("MainWindow", "Y GATA H4", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_21.setText(QtGui.QApplication.translate("MainWindow", "DYS448", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_22.setText(QtGui.QApplication.translate("MainWindow", "DYS456", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_23.setText(QtGui.QApplication.translate("MainWindow", "DYS458", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_24.setText(QtGui.QApplication.translate("MainWindow", "DYS635", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_25.setText(QtGui.QApplication.translate("MainWindow", "YCAIIa", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_26.setText(QtGui.QApplication.translate("MainWindow", "YCAIIb", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "matching", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "save", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

